//
//  Strings.swift
//  Prana21
//
//  Created by Vishal Thakur on 21/11/24.
//

import Foundation


struct AppTexts {
    static let feelingCheckinQuestion = "How are we feeling today?"
    static let crush_Stress = "Crush stress"
    static let sleep_Better = "Sleep Better"
    static let live_longer = "Live longer"
    static let discover = "Discover the hidden"
    static let superpower = "Superpower"
    static let tortoise = "A tortoise breathes"
    static let fourTimesAMinute = "4 times a minute"
    static let andLivesFor = "And lives for"
    static let threeHundredYears = "300 years"
    static let justCorrect = "Just correct"
    static let breathing = "Breathing"
    static let yourBreath = "Your breath is your"
    static let weBreatheEveryDay =  "We breathe everyday"
    static let mostOfUs = "But most of us do it"
    static let wrong = "Wrong"
    static let everWonderedWhy = "Have you ever wondered"
    static let whyMonk = "Why Monk seem so "
    static let calm = "Calm?"
    static let allInBreaths = "It’s all in the breath"
    static let letsLearnTheirSecrets = "Let’s learn all their"
    static let secrets = "Secrets"
    static let welcomeTo = "WELCOME TO"
    static let whyBreathing = "Why breathing"
    static let matters = "Matters?"
    static let itsHow = "It's how your"
    static let brainBody = "Brain and Body"
    static let communicate = "communicate"
    static let properBreathing = "Proper breathing activates the"
    static let vagusNerves = "Vagus nerves"
    static let moreAdrenaline = "More Adrenaline"
    static let fastBreathing = "Fast Breathing"
    static let nervousSystem = "for your Nervous System"
    static let myNameIs = "Hi, my name is"
    static let prana = "Prana!"
    static let yourName = "Your name?"
    static let iAm = "I am 100 years old"
    static let yourBreathScore = "Your Breath"
    static let yourNewBreathScore = "Your new breath"
    static let scoreIsReady = "score is ready"
    static let oldMonk = "male monk"
    static let howOld = "How old are you?"
    static let iRecogniseAs = "I recognise as a"
    static let maleChimera = "male chimera"
    static let whatGender = "What gender do you identify as?"
    static let letsTake = "Let's take"
    static let fiveNaturalBreaths = "5 Natural breaths"
    static let together = "together"
    static let tapEveryTIme = "Tap every time you"
    static let inahaleExhale = "Inhale and Exhale"
    static let mostPeople = "Most people take"
    static let sixteenBreaths = "16-20 BPM"
    static let aMinute = "(breath per minute)"
    static let thatsTooFast = "That’s too fast"
    static let optimalHealth = "for optimal health"
    static let findingYourIdeal = "Find your ideal"
    static let breathingRythm = "Breathing rhythm"
    static let keepingStress = "Keeping stress low &"
    static let energyHigh = "Energy high"
    static let thatWasGreat = "That was great but"
    static let seeAlreaySoMuch = "See, already so"
    static let muchBetter = "much better"
    static let yourImproved  = "Your improved breathing"
    static let whatsTheBenefit = "what’s the benefit?"
    static let deStress = "De-stress, calm mind, better sleep & sharper focus"
    static let youCanDoBetter = "you can do better"
    static let yourBreathing = "Your breathing"
    static let statistics = "statistics"
    static let readyToMakeYourBreath = "Ready to make your breath"
    static let evenBetter = "even better?"
    static let areasToFocus = "Areas you tend to focus on in your workouts"
    static let totalBreathinTime = "Total Breathing Time"
    static let longestBreath = "Longest Breath"
    static let averageExhaleTime = "Average Exhale Time"
    static let averageInhaleTime = "Average Inhale Time"
    static let shortestBreath = "Shortest Breath"
    static let letsPractice = "Let’s practice"
    static let correctBreathing = "correct breathing"
    static let takeAMoment = "Take a moment to check in with yourself"
    static let hasYourMoodShifted = "Has your mood shifted after practising belly breathing?"
    static let excited = "Excited"
    static let content = "Content"
    static let frustrated  = "Frustrated"
    static let overwhelmed  = "Overwhelmed"
    static let worried = "Worried"
    static let fatigued  = "Fatigued"
    static let firstStep = "The first step toward change is awareness"
    
    static let secondstep = "The second step is"
    static let acceptance = "acceptance"
    static let slowBreathing = "Slow Breathing"
    static let lowCortisol = "Less Cortisol = Less Stress"
    static let balancingTheTwo = "balancing the two is"
    static let ultimateLifeHack = "the ultimate life hack"
    static let hack = "Hack your breathing that"
    static let anytime = "any time"
    static let shiftsEnergy = "shifts your energy, focus"
    static let wellbeing = "& wellbeing"
    static let keepStressAtBay = "keeps stress at bay"
    static let especiallyInLifes = "especially in life’s "
    static let inBetweenMoments = "in-between moments"
    static let mindfulBreaths = "Few mindful breaths at"
    static let buildingHabits = "Building Habits is a"
    static let science = "science"
    static let spareMoment = "every spare moment is "
    static let opportunity = "an opportunity"
    static let worldFirst = "World’s first science-based"
    static let scienceBased = "habit forming app"
    static let turningSpareMoments = "turning your spare moments"
    static let toMindfulBreaths = "to mindful breaths"
    static let jusReset = "Let’s reset your breath in "
    static let sevenDays = "Just 7 days!"
    static let fiveBreaths = "Just 5 breaths,"
    static let threeTimesDay = "3 times a day"
    static let guideYou = "We will guide you on making"
    static let breathingLifeStyle = " breathing a lifesyle"
    static let keepYouOnTrack = "We’ll keep you on track"
    static let oneBreathTime  = "one breath at a time"
    static let threeXChances = "3X your chance of"
    static let habits = "building habits"
    static let enableNotifications = "Enable notifications & make every pause a breath"
    static let freshAir  = "of fresh air"
}

struct AppActions {
    static let getStarted = "Get Started"
    static let signUp = "SIGN UP"
    static let signIn = "SIGN IN"
    static let loginWithApple = "SIGN IN WITH APPLE"
    static let next = "Next"
    static let letsGo = "Let's start"
    static let ready = "Ready?"
    static let how = "How?"
    static let what = "What?"
    static let why = "Why?"
    static let really = "Really!"
    static let shocked = "Shocked?"
    static let yes = "YESSS!"
    static let go = "Go!"
    static let continueAction = "continue"
    static let great = "Great!"
    static let more = "More"
    static let join  = "Join"
    static let knowMore = "know more?"
    static let knowHow  = "Know how?"
    static let iAmIn = "I am in!"
    static let letsDoIt = "Let’s do it"
    static let enableNotifications = "Enable notifications"
}
